### PR TITLE
feat: Switch the workload to use java modules

### PR DESCRIPTION
**Pull request by radoslaw-orlowski**
#### 📲 What

Fix problems with switching the workload to use the modularised stacks

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Review by guillermogutierrez — CHANGES_REQUESTED** [review]
Test-api packages for the events workload are not following the same package naming than the other two workloads. 
To unify the package naming across all workloads and the application source code as well. Maybe we should rename the api-test package from **com.amido.stacks** to **com.amido.workloads** for the api-test and api-test-karate

**Review by guillermogutierrez — APPROVED** [review]

**Comment by radoslaw-orlowski** [comment]
👍

**Pull request merged**
